id: P009522
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:36:16.283695
source_metadata:
  id: bdr:W21679
  title: བོད་ཀྱི་དམངས་སྲོལ་གཅེས་བཏུས
  author: ''
  volumes:
    0d30db203d684902be53bbf0233cb8c1:
      image_group_id: I4782
      title: ''
      volume_number: 1
      total_pages: 658
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
