id: IBA0A661C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:27:11+00:00'
last_modified: '2022-06-08T11:37:46.364987+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21679
  title: བོད་ཀྱི་དམངས་སྲོལ་གཅེས་བཏུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    01CB:
      image_group_id: I4782
      title: ''
      total_pages: 658
      order: 1
      base_file: 01CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
